[package]
name = "cli_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battleship_game_lib = { path = "../battleship_game_lib" }
crossterm = "0.27.0"
ratatui = "0.24.0"
anyhow = "1.0.79"

